# Generated by Django 5.2.17 on 2026-09-19 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('CANCELADO', 'Cancelado')], default='EN_COLA', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='ingrediente_cantidad_no_negativa')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='restaurant.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_pago', to='restaurant.itempedido')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='restaurant.pago')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='restaurant.pedido'),
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puntaje_carga_preparacion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='plato_precio_no_negativo')],
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedidos', to='restaurant.plato'),
        ),
        migrations.CreateModel(
            name='ComposicionPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='restaurant.ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicion', to='restaurant.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='restaurant.mesa')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='restaurant.sesion'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta', to='restaurant.sesion'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('MESERO', 'Mesero'), ('COCINERO', 'Cocinero')], max_length=8)),
                ('cuenta_acceso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_restaurante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sesion',
            name='mesero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='restaurant.usuario'),
        ),
        migrations.CreateModel(
            name='ComposicionItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones_items', to='restaurant.ingrediente')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicion', to='restaurant.itempedido')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item_pedido', 'ingrediente'), name='ingrediente_unico_por_item'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='composicion_item_cantidad_positiva')],
            },
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='item_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ('EN_COLA', 'EN_PREPARACION', 'LISTO', 'CANCELADO'))), name='item_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='composicionplato',
            constraint=models.UniqueConstraint(fields=('plato', 'ingrediente'), name='ingrediente_unico_por_plato'),
        ),
        migrations.AddConstraint(
            model_name='composicionplato',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_requerida__gt', 0)), name='composicion_plato_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('rol__in', ('ADMIN', 'MESERO', 'COCINERO'))), name='usuario_rol_valido'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_hora_fin__isnull', True)), fields=('mesa',), name='una_sesion_activa_por_mesa'),
        ),
    ]
