# Generated by Django 5.2.17 on 2026-09-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='puntaje_carga_preparacion',
        ),
    ]
